export { default as Dashboard } from './Dashboard/Dashboard';
export { default as Kanban } from './Other/Kanban';
export { default as Videos } from './Video/Videos';
export { default as Users } from './Users/Users';
export { default as Editor } from './Other/Editor';
export { default as ColorPicker } from './Other/ColorPicker';
export { default as Calendar } from './Calendar/Calendar';
export { default as Bar } from './Charts/Bar';
export { default as ColorMapping } from './Charts/ColorMapping';
export { default as Financial } from './Charts/Financial';
export { default as Line } from './Charts/Line';
export { default as Pie } from './Charts/Pie';
export { default as Area } from './Charts/Area';
export { default as Pyramid } from './Charts/Pyramid';
export { default as Stacked } from './Charts/Stacked';
export { default as Uploader } from './Uploader/SingleVideo/Uploader';
export { default as Signup } from './Signup/Signup';
export {default as EditVideo} from './EditVideo/EditVideo';
export {default as EditWebseries} from './EditWebseries/EditWebseries';
export { default as WebseriesUpload } from './Uploader/WebSeriesVideo/Webseries';
export { default as CreateWebseriesCategory } from './Uploader/WebSeriesVideo/CreateWebseriesCategory';
export { default as CreateVideoCategory } from './Uploader/SingleVideo/CreateVideoCategory';
export { default as Webseries} from './Webseries/Webseries';